### ISSUE TITLE
Failed to activate the language-autohotkey package

### ISSUE THREAD

**Issue by AdenFlorian** [nshakin/language-autohotkey#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [language-autohotkey](https://github.com/nshakin/language-autohotkey) package, v0.1.0

### Stack Trace

Failed to activate the language-autohotkey package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\David\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:1:1)
  at C:\Users\David\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:5:3
  at Object.<anonymous> (C:\Users\David\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:52:5)
  at Object.<anonymous> (C:\Users\David\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\David\.atom\packages\language-autohotkey\lib\language-autohotkey.coffee:1:26)
  at Object.<anonymous> (C:\Users\David\.atom\packages\language-autohotkey\lib\language-autohotkey.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:709:34)
  at Package.module.exports.Package.activateConfig (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:257:12)
  at Package.module.exports.Package.activateNow (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:236:14)
  at C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:222:20)
  at C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\David\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:06.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.0 language-autohotkey:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true,
    "projectHome": "A:\\projects"
  }
}
```

### Installed Packages

```coffee
# User
language-autohotkey, v0.1.0
pigments, v0.8.1

# Dev
No dev packages
```

**Comment by zacps** [comment]
@AdenFlorian This has been fixed in #18 by vanillaSprinkles
