### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ddidderr** [nshakin/language-autohotkey#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**Thrown From**: [language-autohotkey](https://github.com/nshakin/language-autohotkey) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At C:\Users\ddidderr\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\ddidderr\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:4:199)
  at C:\Users\ddidderr\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:5:3
  at Object.<anonymous> (C:\Users\ddidderr\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:52:5)
  at Object.<anonymous> (C:\Users\ddidderr\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\ddidderr\.atom\packages\language-autohotkey\lib\language-autohotkey.coffee:1:26)
  at Object.<anonymous> (C:\Users\ddidderr\.atom\packages\language-autohotkey\lib\language-autohotkey.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package.js:759:34)
  at Package.module.exports.Package.activateConfig (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package.js:261:14)
  at PackageDetailView.module.exports.PackageDetailView.activate (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:150:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:187:12)
  at C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:232:24
  at Emitter.module.exports.Emitter.emit (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\settings-view\lib\package-manager.js:587:27)
  at C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\settings-view\lib\package-manager.js:378:26
  at exit (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\ddidderr\AppData\Local\atom\app-1.0.5\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  4x -2:01.8.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
  4x -2:00.4.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
  5x -1:55.9.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
  2x -1:54.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:53.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:52.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:50.8.0 core:close (atom-text-editor.editor.is-focused)
     -1:38.7.0 settings-view:open (atom-pane.pane.active)
 14x -0:43.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ejoso** [comment]
has there been any movement on this?

**Comment by gk0r** [comment]
Yep, pretty broken. Doesn't work...

**Comment by Gubith** [comment]
Resolved by modifying package.json

Removed entries not present in other (working) language files...

`"main": "./lib/language-autohotkey",`

`"activationEvents": [
    "language-autohotkey:toggle"
  ],`

`".coffee": [
        "lib\\language-autohotkey-view.coffee",
        "lib\\language-autohotkey.coffee"
],`

Changed version by adding +
`"version": "0.1.0+",`

Resulting in attached:
[package.json.txt](https://github.com/nshakin/language-autohotkey/files/245737/package.json.txt)

I read something about fixing this issue by modifying the /lib entries, but was not sure what to change them to, so I just removed them.   No more errors, syntax is highlighted, have not tested further yet.

**Comment by Gubith** [comment]
Also, there's a fork with the same name.  It is currently not in the Atom repository.
https://github.com/cescue/language-autohotkey
