### ISSUE TITLE
Failed to load the language-autohotkey package

### ISSUE THREAD

**Issue by soulomoon** [nshakin/language-autohotkey#24]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [language-autohotkey](https://github.com/nshakin/language-autohotkey) package, v0.1.0
### Stack Trace

Failed to load the language-autohotkey package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\soulomoon\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:1:1)
  at C:\Users\soulomoon\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:5:3
  at Object.<anonymous> (C:\Users\soulomoon\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:52:5)
  at Object.<anonymous> (C:\Users\soulomoon\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:1:1)
  at Module._compile (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\soulomoon\.atom\packages\language-autohotkey\lib\language-autohotkey.coffee:1:26)
  at Object.<anonymous> (C:\Users\soulomoon\.atom\packages\language-autohotkey\lib\language-autohotkey.coffee:1:1)
  at Module._compile (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
  at C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
  at Package.module.exports.Package.measure (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
  at Package.module.exports.Package.load (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:536:30)
  at C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
  at exit (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
  at ChildProcess.<anonymous> (C:\Users\soulomoon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:237:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
     -1:14.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:14 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -1:08.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:59 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:59 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:56.8.0 grammar-selector:show (atom-text-editor.editor)
     -0:54.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:54.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:53.3.0 grammar-selector:show (atom-text-editor.editor)
  4x -0:45.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:40.3.0 pane:show-next-recently-used-item (atom-text-editor.editor.is-focused)
     -0:39.5.0 pane:move-active-item-to-top-of-stack (atom-text-editor.editor.mini.is-focused)
  4x -0:39.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  6x -0:38 core:move-up (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
language-autohotkey, v0.1.0

# Dev
No dev packages
```

**Comment by Wirus-deleted-my-username** [comment]
Same.

```
 Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/Kuba/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
    at file:///C:/Users/Kuba/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:5:3
    at Object.<anonymous> (file:///C:/Users/Kuba/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:5:3)
    at Object.<anonymous> (file:///C:/Users/Kuba/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
    at Module._compile (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Kuba/.atom/packages/language-autohotkey/lib/language-autohotkey.coffee:1:26)
    at Object.<anonymous> (file:///C:/Users/Kuba/.atom/packages/language-autohotkey/lib/language-autohotkey.coffee:1:1)
    at Module._compile (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:721:27)
    at C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:460:29
    at exit (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Kuba\AppData\Local\atom\app-1.11.2\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by jwfu** [comment]
I got the same error but it doesn't seem to prevent the syntax highlighting from working

**Comment by joedf** [comment]
lol.... Read the "readme"

> This project is no longer maintained. Please visit cescue's fork for the latest updates: https://github.com/cescue/language-autohotkey

**EDIT:** Okay true... both are now abandonned... Check out these alternatives:
1. https://github.com/vanillaSprinkles/atom.language-autohotkey
2. https://github.com/ahkscript/SublimeAutoHotkey
3. https://github.com/ahkscript/AutoHotkey-Editors

**Comment by WilJames** [comment]
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.14.4 x64
> **Electron**: 1.3.13
> **OS**: Unknown Windows version
> **Thrown From**: [language-autohotkey](https://github.com/nshakin/language-autohotkey) package 0.1.0
> 
> 
> ### Stack Trace
> 
> Failed to load the language-autohotkey package
> 
> ```
> At Cannot read property 'prototype' of undefined
> 
> TypeError: Cannot read property 'prototype' of undefined
>     at extend (/packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
>     at /packages/language-autohotkey/lib/language-autohotkey-view.coffee:4:7
>     at /packages/language-autohotkey/lib/language-autohotkey-view.coffee:19:11)
>     at /packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
>     at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
>     at /app.asar/src/compile-cache.js:216:21)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (/app.asar/src/native-compile-cache.js:50:27)
>     at /packages/language-autohotkey/lib/language-autohotkey.coffee:1:26)
>     at /packages/language-autohotkey/lib/language-autohotkey.coffee:1:1)
>     at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
>     at /app.asar/src/compile-cache.js:216:21)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (/app.asar/src/native-compile-cache.js:50:27)
>     at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
>     at /app.asar/src/package.js:123:28
>     at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
>     at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
>     at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
>     at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
>     at /app.asar/src/package-manager.js:352:19
>     at /app.asar/src/config.js:635:20
>     at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
>     at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
>     at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
>     at Config.module.exports.Config.endTransaction (/app.asar/src/config.js:354:19)
>     at Config.module.exports.Config.transact (/app.asar/src/config.js:314:14)
>     at Config.module.exports.Config.resetUserSettings (/app.asar/src/config.js:563:19)
>     at Config.module.exports.Config.loadUserConfig (/app.asar/src/config.js:474:16)
>     at later (/app.asar/node_modules/underscore/underscore.js:724:25)
> ```
> 
> ### Commands
> 
> ```
>   2x -8:16.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
>      -8:08.8.0 grammar-selector:show (atom-text-editor.editor)
>      -8:03.0 editor:consolidate-selections (input.hidden-input)
>      -8:03.0 core:cancel (input.hidden-input)
>      -4:34.1.0 atom-beautify:beautify-editor (input.hidden-input)
>   4x -1:35.1.0 symbols-tree-view:toggle (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> 
> ```
> atom-beautify 0.29.17 
> auto-encoding 0.6.3 
> file-icons 2.0.17 
> highlight-selected 0.12.0 
> indent-guide-improved 1.4.12 
> language-autohotkey 0.1.0 
> language-ini 1.18.0 
> language-lua 0.9.11 
> language-lua-wow 0.2.0 
> linter 1.11.23 
> linter-lua 1.0.2 
> linter-lua-findglobals 1.2.0 
> linter-luaparse 0.2.0 
> markdown-preview-plus 2.4.9 
> minimap 4.26.8 
> minimap-highlight-selected 4.5.0 
> minimap-split-diff 0.3.6 
> pdf-view 0.55.0 
> split-diff 1.2.0 
> symbols-tree-view 0.13.2 
> ```
> 
>

**Comment by tatoosh** [comment]
Error by installing:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: A2015011
**Thrown From**: [language-autohotkey](https://github.com/nshakin/language-autohotkey) package 0.1.0


### Stack Trace

Failed to load the language-autohotkey package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
    at /packages/language-autohotkey/lib/language-autohotkey-view.coffee:4:7
    at /packages/language-autohotkey/lib/language-autohotkey-view.coffee:19:11)
    at /packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/language-autohotkey/lib/language-autohotkey.coffee:1:26)
    at /packages/language-autohotkey/lib/language-autohotkey.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:17.4.0 grammar-selector:show (input.hidden-input)
     -1:15.3.0 editor:consolidate-selections (input.hidden-input)
     -1:15.3.0 core:cancel (input.hidden-input)
     -1:15.2.0 editor:consolidate-selections (input.hidden-input)
     -1:15.2.0 core:cancel (input.hidden-input)
     -0:52.9.0 settings-view:uninstall-packages (input.hidden-input)
     -0:47.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
git-control 0.8.2 
git-plus 7.3.3 
language-autohotkey 0.1.0 
language-groovy 0.6.0 
language-jpl 0.1.0 
```

**Comment by cescue** [comment]
Sorry about my repo getting lost to the void. I merged a couple of github accounts without forking all of my repos to the new account.

FWIW, my repo is back up at its original location, and the package should now be available via the Atom package manager as `language-autohotkey2`.  The name isn't ideal, but `language-autohotkey` and `language-ahk` were both taken.

Cheers!

**Comment by dragonfoxsl** [comment]
Had the same problem installed `language-autohotkey2` and now it works. Thanks @cescue
