### ISSUE TITLE
Failed to load autohot-key package

### ISSUE THREAD

**Issue by daniele-aveta** [nshakin/language-autohotkey#25]
TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/Daniele/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
    at file:///C:/Users/Daniele/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:5:3
    at Object.<anonymous> (file:///C:/Users/Daniele/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:5:3)
    at Object.<anonymous> (file:///C:/Users/Daniele/.atom/packages/language-autohotkey/lib/language-autohotkey-view.coffee:1:1)
    at Module._compile (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:UsersDanieleAppDataLocalatomapp-1.9.8resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Daniele/.atom/packages/language-autohotkey/lib/language-autohotkey.coffee:1:26)
    at Object.<anonymous> (file:///C:/Users/Daniele/.atom/packages/language-autohotkey/lib/language-autohotkey.coffee:1:1)
    at Module._compile (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:UsersDanieleAppDataLocalatomapp-1.9.8resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package.js:715:27)
    at C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
    at exit (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Daniele\AppData\Local\atom\app-1.9.8\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by SabeelM** [comment]
anyone found solution to this? same issue for me

**Comment by daniele-aveta** [comment]
> anyone found solution to this? same issue for me

@SabeelM Hey, if you're still wondering they dropped support for this plugin years ago (old me didn't know either lol)! If you go to the repository page you'll see they've linked the new one on top of their readme.md! It seems to work just fine! Hope you'll fix with it too! :) I'll link it down here!

https://github.com/cescue/language-autohotkey

**Comment by SabeelM** [comment]
> > anyone found solution to this? same issue for me
> 
> @SabeelM Hey, if you're still wondering they dropped support for this plugin years ago (old me didn't know either lol)! If you go to the repository page you'll see they've linked the new one on top of their readme.md! It seems to work just fine! Hope you'll fix with it too! :) I'll link it down here!
> 
> https://github.com/cescue/language-autohotkey

Aha, thanks a lot I'll take a look :)
